class Lumen::Language < Struct.new(:code, :name)
  # Labels:
  #   https://en.wikipedia.org/w/index.php?title=List_of_ISO_639-1_codes
  #
  def self.all
    [
      new('af', 'Afrikaans'),
      new('am', 'Amharic'),
      new('ar', 'Arabic'),
      new('ar-EG', 'Arabic (Egypt)'),
      new('az', 'Azerbaijani'),
      new('be', 'Belarusian'),
      new('bg', 'Bulgarian'),
      new('bn', 'Bengali'),
      new('bs', 'Bosnian'),
      new('ca', 'Catalan; Valencian'),
      new('crp', 'Mauritian Creole'),
      new('cs', 'Czech'),
      new('cy', 'Welsh'),
      new('da', 'Danish'),
      new('de', 'German'),
      new('de-AT', 'German (Austria)'),
      new('de-BL', 'German (Belgium)'),
      new('de-CH', 'German (Switzerland)'),
      new('el', 'Greek, Modern'),
      new('en-AU', 'English (Australia)'),
      new('en-BL', 'English (Belgium)'),
      new('en-CA', 'English (Canada)'),
      new('en-GB', 'English (Great Britain)'),
      new('en-IN', 'English (India)'),
      new('en-IE', 'English (Ireland)'),
      new('en-MY', 'English (Malaysia)'),
      new('en-NZ', 'English (New Zealand)'),
      new('en-ZA', 'English (South Africa)'),
      new('en-SG', 'English (Singapore)'),
      new('en-CH', 'English (Switzerland)'),
      new('en', 'English'),
      new('eo', 'Esperanto'),
      new('es', 'Spanish; Castilian'),
      new('es-419', 'Spanish (Latin America)'),
      new('et', 'Estonian'),
      new('eu', 'Basque'),
      new('fa', 'Farsi'),
      new('fi', 'Finnish'),
      new('fil', 'Filipino'),
      new('fr', 'French'),
      new('fr-BL', 'French (Belgium)'),
      new('fr-CA', 'French (Canada)'),
      new('fr-CH', 'French (Switzerland)'),
      new('ga', 'Irish'),
      new('gl', 'Galician'),
      new('gu', 'Gujarati'),
      new('hi', 'Hindi'),
      new('hr', 'Croatian'),
      new('ht', 'Haitian; Haitian Creole'),
      new('hu', 'Hungarian'),
      new('hy', 'Armenian'),
      new('id', 'Indonesian'),
      new('is', 'Icelandic'),
      new('it', 'Italian'),
      new('iw', 'Hebrew'),
      new('ja', 'Japanese'),
      new('ka', 'Georgian'),
      new('kk', 'Kazakh'),
      new('km', 'Khmer'),
      new('kn', 'Kannada'),
      new('ko', 'Korean'),
      new('ky', 'Kyrgyz'),
      new('lt', 'Lithuanian'),
      new('lv', 'Latvian'),
      new('la', 'Latin'),
      new('lg', 'Luganda'),
      new('lo', 'Lao'),
      new('mg', 'Malagasy'),
      new('mk', 'Macedonian'),
      new('ml', 'Malayalam'),
      new('ms', 'Malay'),
      new('mt', 'Maltese'),
      new('my', 'Burmese (Myanmar)'),
      new('ne', 'Nepali'),
      new('nl', 'Dutch'),
      new('nl-BL', 'Dutch (Belgium)'),
      new('no', 'Norwegian'),
      new('nn', 'Norwegian (Nynorsk)'),
      new('or', 'Oriya'),
      new('pa', 'Punjabi'),
      new('pl', 'Polish'),
      new('pt', 'Portuguese'),
      new('pt-BR', 'Portuguese (Brazil)'),
      new('rm', 'Rhaeto-Romance'),
      new('ro', 'Romanian'),
      new('ru', 'Russian'),
      new('rw', 'Kinyardwanda'),
      new('si', 'Sinhala'),
      new('sk', 'Slovak'),
      new('sl', 'Slovene'),
      new('sq', 'Albanian'),
      new('sr', 'Serbian'),
      new('sv', 'Swedish'),
      new('sw', 'Swahili'),
      new('ta', 'Tamil'),
      new('th', 'Thai'),
      new('tl', 'Tagalog'),
      new('tr', 'Turkish'),
      new('uk', 'Ukrainian'),
      new('ur', 'Urdu'),
      new('uz', 'Uzbek'),
      new('vi', 'Vietnamese'),
      new('yi', 'Yiddish'),
      new('yo', 'Yoruba'),
      new('zh', 'Chinese'),
      new('zh-Hans', 'Chinese (Simplified)'),
      new('zh-Hant', 'Chinese (Traditional)'),
      new('zh-HK', 'Chinese (Hong Kong)'),
      new('zh-MS', 'Chinese (Malay)'),
      new('zh-HG', 'Chinese (Singapore)'),
      new('zu', 'Zulu')
    ]
  end

  def self.codes
    all.map(&:code)
  end

  def label
    "#{code} - #{name}"
  end
end
