# Configuration:
# 
# disabled
#   false if tracking tag should be shown
# use_async
#   Set to true if you want to use asynchronous tracking
# url
#   The url of your piwik instance (e.g. localhost/piwik/
# id_site
#   The id of your website inside Piwik
#
production:
  piwik:
    id_site: 3
    url: stats.berkman.harvard.edu
    use_async: false
    disabled: false

development:
  piwik:
    id_site: 4
    url: stats.berkman.harvard.edu
    disabled: false
    use_async: false

test:
  piwik:
    id_site: 4
    url: stats.berkman.harvard.edu
    disabled: true
    use_async: false
    hostname: localhost
